services:
  web:
    image: pablosla/work-from-home-web:latest
    container_name: work-from-home-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - postgres
    networks:
      - acciona
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wfh.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.wfh.entrypoints=web"
      - "traefik.http.services.wfh.loadbalancer.server.port=3000"
        

  postgres:
    image: postgres:18.3
    container_name: work-from-home-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - acciona

volumes:
  postgres_data:

networks:
  acciona:
    external: true
