global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Métricas de Prometheus mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas de un reader
  - job_name: 'node-api'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['reader-api:3001']
        labels:
          application: 'node-api'

  # Métricas de la api en java
  - job_name: 'java-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['java-api:8080']
        labels:
          application: 'java-api'
